export HISTFILESIZE=1000
export HISTSIZE=1000
# Ignore duplicate commands and whitespace in history
export HISTCONTROL=ignoreboth
# Keep the times of the commands in history
export HISTTIMEFORMAT='%F %T  '

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

export IGNOREEOF=2

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  export LC_ALL='en_US.UTF-8'
fi

# External

test -e "${HOME}/.bashrc_local" && source "${HOME}/.bashrc_local"

# Aliases

alias ..="cd .."
alias ~="cd ~"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  alias ls="command ls --color"
else # OS X `ls`
  alias ls="command ls -G"
fi
alias ll="ls -lF"
alias la="ls -laF"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vim="vim"
alias mux="tmuxinator"
alias brwe="brew"

# Bash configuration

# Autocorrect fudged paths in cd calls
shopt -s cdspell
# Update columns and rows if window size changes
shopt -s checkwinsize
# Put multi-line commands onto one line of history
shopt -s cmdhist
# Include dotfiles in pattern matching
shopt -s dotglob
# Enable advanced pattern matching
shopt -s extglob
# Append rather than overwrite Bash history
shopt -s histappend
# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# These options only exist since Bash 4.0-alpha
if ((BASH_VERSINFO[0] == 4)) ; then
  # Autocorrect fudged paths during completion
  shopt -s dirspell
  # Enable double-starring paths
  shopt -s globstar
  # Warn me about stopped jobs when exiting; only if >=4.1 due to bug
  # <https://lists.gnu.org/archive/html/bug-bash/2009-02/msg00176.html>
  if ((BASH_VERSINFO[1] >= 1)) ; then
    shopt -s checkjobs
  fi

  # Expand variables in directory completion; only available since 4.3
  if ((BASH_VERSINFO[1] >= 3)) ; then
    shopt -s direxpand
  fi
fi


# Completion

# Bash builtins
complete -A builtin builtin

# Bash options
complete -A setopt set

# Commands
complete -A command command complete coproc exec hash type

# Directories
complete -A directory cd pushd mkdir rmdir

# Functions
complete -A function function

# Help topics
complete -A helptopic help

# Jobspecs
complete -A job disown fg jobs
complete -A stopped bg

# Readline bindings
complete -A binding bind

# Shell options
complete -A shopt shopt

# Signal names
complete -A signal trap

# Variables
complete -A variable declare export readonly typeset

# Both functions and variables
complete -A function -A variable unset

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for many Bash commands
if which brew &> /dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
  source "$(brew --prefix)/etc/bash_completion";
elif [ -f /usr/share/bash-completion/bash_completion ]; then
  source /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
  source /etc/bash_completion;
fi;

complete -cf sudo


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
