# Source interactive Bash config if it exists
test -e "${HOME}/.bashrc" && source "${HOME}/.bashrc"

# Iterm2 integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

export PATH="$HOME/.poetry/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
